### ISSUE TITLE
intron doesn't always extend to first exon

### ISSUE THREAD

**Issue by acthp** [AkhilKamath/ucsc-xena-client#1]
In ERG transcripts 1, 2, 3, 5, 6, the intron annotation does not extend all the way to the left-most exon, as it should.

![erg](https://user-images.githubusercontent.com/494506/27943351-413305f2-6293-11e7-9571-4c1d7ab791b7.png)

**Comment by AkhilKamath** [comment]
Sorry about that. I have pushed the code for this.
