### ISSUE TITLE
Exon in wrong place, or mislabeled

### ISSUE THREAD

**Issue by acthp** [AkhilKamath/ucsc-xena-client#2]
ERG exon 11 is to the right of exon 12, in the 5th transcript. It's either positioned incorrectly, or labeled incorrectly.

![erg](https://user-images.githubusercontent.com/494506/27943397-b5be0b06-6293-11e7-8235-26a1de503bfb.png)

**Comment by AkhilKamath** [comment]
It was because of a small bug in the padding code. Resolved it.
