### ISSUE TITLE
gap at cds in single exon

### ISSUE THREAD

**Issue by acthp** [AkhilKamath/ucsc-xena-client#3]
There's a visible gap between the big/small boxes of an exon that spans cds. Shown here on TP53.

Looks like an off-by-one bug, possibly dependent on strand.

![exongap](https://user-images.githubusercontent.com/494506/27943518-c5c0b3ea-6294-11e7-8827-814e49ec9686.png)

**Comment by AkhilKamath** [comment]
That's strange. Here is how it looks like when I'm viewing it on the dev server.
![3](https://user-images.githubusercontent.com/14125785/27963566-1acf1070-6353-11e7-801d-d631536aa94e.png)

**Comment by AkhilKamath** [comment]
I removed the black border to see if the gap appears, but it does not. Is the gap visible on all small/big box pairs that spans cdsStart/End ?
