### ISSUE TITLE
refactor bigBox, smallBox

### ISSUE THREAD

**Issue by acthp** [AkhilKamath/ucsc-xena-client#7]
As per email, change bigBox, smallBox to return the computed parameters in a data structure, like
```[type, label, width, origin, position]``` or ```{type, label, width, origin, position}```.

Render to jsx like ```exonShape(...).map(renderExon)```, where ```renderExon``` is a new function that takes the data structure and returns ```<div ...><span...>{label}</div></span>```.

**Comment by AkhilKamath** [comment]
thanks, done.
